### PR TITLE
upmerge: merge up to the commit: b4c76b3e1

### PR DESCRIPTION
**Pull request by lmaciejonczyk**

### CODE REVIEW

**Review by rlubos — COMMENTED** [review]
I see you're merging directly from https://github.com/openthread/openthread, I don't think we should do that. For this repo, the upstream is https://github.com/zephyrproject-rtos/openthread, I think we might run into trouble if we need to upmerge again from that fork, for instance to pull some changes specific to the Zephyr fork (like the integration layer) - not sure what will happen if we try to merge the same commits again.

@edmont has just upmerged https://github.com/zephyrproject-rtos/openthread, so it should be quite fresh, perhaps it'd be enough just to update the OT SHA and stick to the upstream?

**Comment by rlubos** [comment]
> I see you're merging directly from https://github.com/openthread/openthread, I don't think we should do that. For this repo, the upstream is https://github.com/zephyrproject-rtos/openthread, I think we might run into trouble if we need to upmerge again from that fork, for instance to pull some changes specific to the Zephyr fork (like the integration layer) - not sure what will happen if we try to merge the same commits again.
> 
> @edmont has just upmerged https://github.com/zephyrproject-rtos/openthread, so it should be quite fresh, perhaps it'd be enough just to update the OT SHA and stick to the upstream?

Ok, scratch that - discussed F2F and agreed to upmerge with vanilla OT this time.

**Review by rlubos — APPROVED** [review]

**Comment by rlubos** [comment]
Actually, one request, I missed that one. Please add `[nrf mergeup]` sauce tag to the merge commit title.

**Comment by edmont** [comment]
@lmaciejonczyk can this stale PR be closed?

**Pull request closed without merging**
